// StockExchange.AngularUI/src/app/components/solicitacao/solicitacao.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { CdbService } from '../../services/cdb.service';
import { RetornoModel } from '../../models/retorno.model';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatSnackBar } from '@angular/material/snack-bar';

@Component({
    selector: 'app-solicitacao',
    standalone: false,
    templateUrl: './solicitacao.component.html',
    styleUrl: './solicitacao.component.css',
    encapsulation: ViewEncapsulation.None // // 2025/04/22 - To view the component CSS
})
export class SolicitacaoComponent {
    solicitacaoForm: FormGroup;
    retornoModel: RetornoModel = {resultadoBruto:'0', resultadoLiquido:'0'} as RetornoModel;
    validationMessage: string = "";

    constructor(private readonly formBuilder: FormBuilder, private readonly cdbService: CdbService, private readonly snackBar: MatSnackBar) {
        this.solicitacaoForm = this.formBuilder.group({
            investimento: ['', [Validators.required, Validators.min(0.01)]], // Only values greater than 0.01
            meses: ['', [Validators.required, Validators.pattern('^[0-9]+$'), Validators.min(2), Validators.max(1200)]] // Only positive integers between 2 and 1200
        });
    }

    private validaEstrutura(): { investimento: number, meses: number } | null {
        if (this.solicitacaoForm.valid) {
            // Valida o parâmetro investimento
            const investimentoFormatado = this.solicitacaoForm.get('investimento')?.value;
    
            const investimento = typeof investimentoFormatado === 'number'
                ? investimentoFormatado
                : parseFloat(
                    investimentoFormatado
                        .replace('R$', '')
                        .replace(/\./g, '')
                        .replace(',', '.')
                        .trim()
                );
            
            // Valida o parâmetro meses
            const mesesFormatado = this.solicitacaoForm.get('meses')?.value;
    
            const meses = typeof mesesFormatado === 'number'
                ? mesesFormatado
                : parseFloat(
                    mesesFormatado
                        .replace(/\./g, '')
                        .replace('.', '')
                        .replace(',', '')
                        .trim()
                );

            // Retorna os parametros válidos
            return { investimento, meses };
        }
    
        // Retorna os parametros inválidos
        return null;
    }
    
    private solicitarCalculoInvestimento(investimento: number, meses: number): void {
        this.cdbService.solicitarCalculoInvestimento(investimento, meses).subscribe({
            next: (res: RetornoModel) => {
                this.retornoModel = res;
    
                this.snackBar.open('Investimento calculado com sucesso!', 'Fechar', {
                    duration: 3000,
                    panelClass: ['mat-primary'],
                    horizontalPosition: 'center',
                    verticalPosition: 'top',
                });
            },
            error: (err) => {
                this.snackBar.open(err.message ?? 'Erro ao calcular investimento.', 'Fechar', {
                    duration: 5000,
                    panelClass: ['mat-warn'],
                    horizontalPosition: 'center',
                    verticalPosition: 'top',
                });
            }
        });
    }

    blockDecimal(event: KeyboardEvent): void {
        if (event.key === '.' || event.key === ',') {
            event.preventDefault();
        }
    }

    clearFields(): void {
        // Clear form fields
        this.solicitacaoForm.reset({
            investimento: 0,
            meses: 0
        });

        // Clear retorno fields
        this.retornoModel = {resultadoBruto:'0', resultadoLiquido:'0'} as RetornoModel;
    }

    onSubmit(): void {
        // Valida os dados de entrada
        const dados = this.validaEstrutura();

        // Se válidos
        if (dados) {
            // Realiza a requisição
            this.solicitarCalculoInvestimento(dados.investimento, dados.meses);
        }
    }    
}

<div class="card">
    <h1>Bem-vindo(a) à Aplicação<br />Angular CDB</h1>
    <div class="internalCard">
        <h2>Solicitar o Calculo do Investimento CDB</h2>
        <form [formGroup]="solicitacaoForm" (ngSubmit)="onSubmit()">
            <mat-form-field class="textField" appearance="outline">
                <mat-label>Investimento</mat-label>
                <input matInput formControlName="investimento"
                    mask="separator.2"
                    thousandSeparator="."
                    decimalMarker=","
                    prefix="R$ "
                    placeholder="Ex: R$ 0,01" />
                <mat-error *ngIf="solicitacaoForm.get('investimento')?.hasError('required')">
                    Campo monetário obrigatório.
                </mat-error>
                <mat-error *ngIf="solicitacaoForm.get('investimento')?.hasError('min')">
                    O valor deve ser maior que R$ 0,00.
                </mat-error>
            </mat-form-field>
            
            <mat-form-field class="textField" appearance="outline">
                <mat-label>Meses</mat-label>
                <input matInput formControlName="meses"
                    type="number"
                    placeholder="Ex: 24"
                    (keydown)="blockDecimal($event)" />
                <mat-error *ngIf="solicitacaoForm.get('meses')?.hasError('required')">
                    Campo numérico obrigatório.
                </mat-error>
                <mat-error *ngIf="solicitacaoForm.get('meses')?.hasError('pattern')">
                    Apenas números inteiros.
                </mat-error>
                <mat-error *ngIf="solicitacaoForm.get('meses')?.hasError('min')">
                    O valor deve ser maior que 1.
                </mat-error>
                <mat-error *ngIf="solicitacaoForm.get('meses')?.hasError('max')">
                    O valor deve ser menor que 1201.
                </mat-error>
            </mat-form-field>

            <button class="buttonSpaceLeft" mat-stroked-button color="primary" type="submit">Solicitar</button>

            <button class="buttonSpaceRight" mat-stroked-button color="primary" (click)="clearFields()">Limpar</button>
        </form>
    </div>
    <div class="internalCard">
        <h2>Resultado do Investimento CDB</h2>
        <dl class="grid">
            <dt>Retorno Bruto:</dt><dd>{{this.retornoModel.resultadoBruto | currency}}</dd>
            <dt>Retorno Líquido:</dt><dd>{{this.retornoModel.resultadoLiquido | currency}}</dd>
        </dl>
    </div>
    <p>
        <a class="link" target="_blank" href="https://github.com/rodrigocdellu/stockexchange.front-end">Para <strong>Maiores Informações</strong> veja meu GitHub!</a>
    </p>
    <figure>
        <figcaption>Desenvolvido Com</figcaption>
        <a class="link" target="_blank" href="https://angular.dev"><img src="Angular.png" alt="Angular" /></a>
        &nbsp;&nbsp;
        <a class="link" target="_blank" href="https://www.typescriptlang.org"><img src="TS.png" alt="TypeScript" /></a>
        &nbsp;&nbsp;
        <a class="link" target="_blank" href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript"><img src="JS.png" alt="JavaScrit" /></a>
        &nbsp;&nbsp;
        <a class="link" target="_blank" href="https://www.w3.org/html"><img src="HTML5.png" alt="HTML 5" /></a>
        &nbsp;&nbsp;
        <a class="link" target="_blank" href="https://www.w3.org/Style/CSS"><img src="CSS3.png" alt="CSS 3" /></a>
    </figure>
</div>

// StockExchange.ReactUI/src/app/components/solicitacao/SolicitacaoComponent.tsx
import { useState } from 'react';
import { CdbService } from '../../services/CdbService';
import { type RetornoModel } from '../../models/RetornoModel';
import styles from './Solicitacao.module.css';
import { NumericFormat, type NumberFormatValues } from 'react-number-format';
import { useForm, Controller } from 'react-hook-form';
import { TextField, Button, Snackbar, Alert } from '@mui/material';

export default function SolicitacaoComponent() {
    const [retornoModel, setRetornoModel] = useState<RetornoModel>();
    const [snack, setSnack] = useState({ open: false, message: '', severity: 'success' });
    const { control, register, handleSubmit, reset, formState: { errors } } = useForm<FormData>();

    type FormData = {
        investimento: number,
        meses: number
    };
    
    function validaEstrutura(formData: FormData): { investimento: number, meses: number } | null {
        // Valida o parâmetro investimento
        const investimentoFormatado = String(formData.investimento);

        const investimento = typeof investimentoFormatado === 'number'
            ? investimentoFormatado
            : parseFloat(
                investimentoFormatado
                    .replace('R$', '')
                    .replace(/\./g, '')
                    .replace(',', '.')
                    .trim()
            );
        
        // Valida o parâmetro meses
        const mesesFormatado = String(formData.meses);

        const meses = typeof mesesFormatado === 'number'
            ? mesesFormatado
            : parseFloat(
                mesesFormatado
                    .replace(/\./g, '')
                    .replace('.', '')
                    .replace(',', '')
                    .trim()
            );

        // Retorna os parametros válidos
        return { investimento, meses };
    }

    function solicitarCalculoInvestimento(investimento: number, meses: number): void {
        new CdbService().solicitarCalculoInvestimento(investimento, meses)
            .then((res) => {
                setRetornoModel(res.data);
                
                setSnack({
                    open: true,
                    message: 'Investimento calculado com sucesso!',
                    severity: 'success'
                });
            })
            .catch((err) => {
                setSnack({
                    open: true,
                    message: err.message || 'Erro ao calcular investimento.',
                    severity: 'error'
                });
            });
    }

    function currencyChange(onChangeFn: (value: number | undefined) => void) {
        return function (values: NumberFormatValues): void {
            onChangeFn(values.floatValue);
        };
    }

    function blockDecimal(event: React.KeyboardEvent<HTMLInputElement>): void {
        if (event.key === '.' || event.key === ',') {
            event.preventDefault();
        }
    }

    function clearFields(): void {
        // Clear form fields
        reset({
            investimento: 0,
            meses: 0
        });
    }

    function onCloseSnack(): void {
        // Close the snack
        setSnack({
            ...snack,
            open: false
        });
    };

    function onSubmit(formData: FormData): void {
        // Valida os dados de entrada
        const dados = validaEstrutura(formData);

        // Se válidos
        if (dados) {
            // Realiza a requisição
            solicitarCalculoInvestimento(dados.investimento, dados.meses);
        }   
    }

    return (
        <div className={styles.card}>
            <h1>Bem-vindo(a) à Aplicação<br />React CDB</h1>
            <div className={styles.internalCard}>
                <h2>Solicitar o Calculo do Investimento CDB</h2>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <Controller
                        name="investimento"
                        control={control}
                        rules={{
                            required: "Campo monetário obrigatório.",
                            min: { value: 0.01, message: "O valor deve ser maior que R$ 0,00." }
                        }}
                        render={({ field }) => (
                            <NumericFormat
                                label="Investimento*"
                                variant="outlined"
                                fullWidth
                                margin="normal"
                                className={styles.textField}
                                error={!!errors.investimento}
                                helperText={errors.investimento?.message}
                                decimalScale={2}
                                thousandSeparator="."
                                decimalSeparator=","
                                prefix="R$ "
                                placeholder="Ex: R$ 0,01"
                                value={field.value ?? ''}
                                customInput={TextField}
                                onValueChange={currencyChange(field.onChange)} />
                        )} />

                    <TextField
                        label="Meses*"
                        variant="outlined"
                        type="number"
                        fullWidth
                        margin="normal"
                        className={styles.textField}
                        error={!!errors.meses}
                        helperText={errors.meses?.message}
                        placeholder="Ex: 24"
                        onKeyDown={blockDecimal}
                        {...register("meses", {
                            required: "Campo numérico obrigatório.",
                            min: {value: 2, message: "O valor deve ser maior que 1."},
                            max: {value: 1200, message: "O valor deve ser menor que 1201."}
                        })} />
                    
                    <Button className={styles.buttonSpaceLeft} variant="outlined" color="primary" type="submit">Solicitar</Button>
                    
                    <Button className={styles.buttonSpaceRight} variant="outlined" color="primary" onClick={clearFields}>Limpar</Button>
                </form>
                <Snackbar
                    open={snack.open}
                    autoHideDuration={snack.severity === 'success' ? 3000 : 5000}
                    anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
                    onClose={onCloseSnack}>
                    <Alert
                        severity={snack.severity as any}
                        sx={{ width: '100%' }}
                        onClose={onCloseSnack}>
                        {snack.message}
                    </Alert>
                </Snackbar>
            </div>
            <div className={styles.internalCard}>
                <h2>Resultado do Investimento CDB</h2>
                <dl className={styles.grid}>
                    <dt>Retorno Bruto:</dt><dd>{retornoModel?.resultadoBruto}</dd>
                    <dt>Retorno Líquido:</dt><dd>{retornoModel?.resultadoLiquido}</dd>
                </dl>
            </div>
            <p>
                <a className={styles.link} target="_blank" href="https://github.com/rodrigocdellu/stockexchange.front-end">Para <strong>Maiores Informações</strong> veja meu GitHub!</a>
            </p>
            <figure>
                <figcaption>Desenvolvido Com</figcaption>
                <a className={styles.link} target="_blank" href="https://react.dev"><img src="React.png" alt="React" /></a>
                &nbsp;&nbsp;
                <a className={styles.link} target="_blank" href="https://vite.dev"><img src="Vite.png" alt="Vite" /></a>
                &nbsp;&nbsp;
                <a className={styles.link} target="_blank" href="https://www.typescriptlang.org"><img src="TS.png" alt="TypeScript" /></a>
                &nbsp;&nbsp;
                <a className={styles.link} target="_blank" href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript"><img src="JS.png" alt="JavaScrit" /></a>
                &nbsp;&nbsp;
                <a className={styles.link} target="_blank" href="https://www.w3.org/html"><img src="HTML5.png" alt="HTML 5" /></a>
                &nbsp;&nbsp;
                <a className={styles.link} target="_blank" href="https://www.w3.org/Style/CSS"><img src="CSS3.png" alt="CSS 3" /></a>
            </figure>
        </div>
    )
}
